assistant_name: "lucy"
language: "en-US"

stt:                        # Speech-to-text
  engine: "speechrecognition"
  recognizer: "google"
  timeout_seconds: 6

tts:                        # Text-to-speech
  engine: "pyttsx3"
  voice: "Zira"

wake_words:
  - "lucy"
  - "hey lucy"

aliases:
  open: ["open", "launch", "start"]

sites:
  youtube: "https://www.youtube.com/"
  google: "https://www.google.com/"
  linkedin: "www.linkedin.com/in/deeptanshu-sharma-5814672b2"
  github: "https://github.com/DeeptanshuSharma1011"

apps:                       # NEW: Local apps Lucy can open
  notepad: "C:\\Windows\\notepad.exe"
  calculator: "C:\\Windows\\WinSxS\\wow64_microsoft-windows-calc_31bf3856ad364e35_10.0.19041.1_none_6a03b910ee7a4073\\calc.exe"
  paint: "C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Accessories\\Paint.lnk"
  discord: "C:\\Users\\LENOVO\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Discord Inc"
  mongodb: "C:\\Users\\LENOVO\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\MongoDB Inc"
  brave: "C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs"
  capcut: "C:\\Users\\LENOVO\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\CapCut"
  whatsapp: "whatsapp.exe"
  word: "C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs"
  protonvpn: "C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Proton"

apis:                       # NEW: API keys for weather & news
  openweather:
    key: "88b914e36fbb17430ab5fc6ce4262d30"
    city: "New Delhi"
  newsapi:
    key: "c95ce95d98994842a10cda53f4e86220"
    country: "in"
